# Generated by Django 3.0.6 on 2020-10-10 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='free',
        ),
        migrations.AddField(
            model_name='material',
            name='likes',
            field=models.ManyToManyField(related_name='Material_op', to=settings.AUTH_USER_MODEL),
        ),
    ]
